### ISSUE TITLE
React .14 throws deprecation warning during assertion

### ISSUE THREAD

**Issue by mrfr0g** [reactjs/react-a11y#101]
The warning is thrown from assertion.js 

```
98:   // There can be false negatives if one of the children is a Component,
99:   // as Components' children are inaccessible until it's is rendered.
100:  // To account for this, check each Component's HTML after it's
101:  // been mounted.
102:  after(child.type.prototype, 'componentDidMount', function () {
103:    assertLabel(React.findDOMNode(this), context, failureCB);
104:  });
```

I took a quick stab at fixing it, but ran into some interesting errors when running tests that I don't have time at the moment to resolve. **ERROR: 'Warning: React can't find the root component node for data-reactid value `.9.0`. If you're seeing this message, it probably means that you've loaded two copies of React on the page. At this time, only a single copy of React can be loaded at a time.'**

**Comment by joeybaker** [comment]
The quick fix is `a11y(ReactDom)` instead of `a11y(React)`

**Comment by benmonro** [comment]
using the ReactDOM trick doesn't work for me, it prevents the findDOMNode warning, but then I get nothing from a11y as a result

**Comment by nickmccurdy** [comment]
I think you're looking for `a11y(React, { ReactDOM })`.

**Comment by erin-doyle** [comment]
I am hoping this work around is no longer needed in the latest v1.0.0.  Please try updating and see if you still have the problem.  I'm going to close this for now but please reply back here if you're still having the issue and I'll reopen it.
