### ISSUE TITLE
It should not warn if a parent has an aria role and a child component has an aria-label

### ISSUE THREAD

**Issue by esoman** [reactjs/react-a11y#105]
I ran across this issue and I would NOT expect a warning to be logged in this case.

```
it('does not warn when a child component is empty label and has an aria-label', () => {
  var Foo = React.createClass({
    render: function() {
      return (
        <span aria-label="test label"/>
      );
    }
  });

  doNotExpectWarning(assertions.render.NO_LABEL.msg, () => {
    React.render(<div role="dialog"><Foo/></div>, fixture);
  });
});
```

It appears the assertion code is only checking for text contents in the case of spans and is not taking into consideration aria-\* attributes or role attributes.  I attempted `role="presentation"` and `role="none"` when rendering `Foo` but I still  received a warning.

Also, I believe there may be an off by one error in the `assertions.assertLabel` code as the following will pass in the previous test:

```
  doNotExpectWarning(assertions.render.NO_LABEL.msg, () => {
    React.render(<div role="dialog"><span>test</span><Foo/></div>, fixture);
  });
```

**Comment by benknight** [comment]
+1

I'm running into this issue only when the first child has no text content.  For example:

```html
<!-- aria-label warning on parent div: -->
<div>
  <span class="icon" aria-label="Close"></span>
  <div>Blah...</div>
</div>
```

However, switching the child order doesn't trigger an `aria-label` warning:

```html
<!-- No warning: -->
<div>
  <div>Blah...</div>
  <span class="icon" aria-label="Close"></span>
</div>
```

**Comment by thecristen** [comment]
+1

I'm experiencing a variant of this problem when trying to make a dropdown menu. Each link starts with a contentless span with `aria-hidden="true"` (think FontAwesome icon), followed by the text of that link. `react-a11y` thinks all these links don't have content.

**Comment by erin-doyle** [comment]
I'll need to do some checking but I'd be curious if after updating to v1.0.0 this is still an issue?

**Comment by erin-doyle** [comment]
I'm going to close this as I'm not sure this is still an issue post v1.0.0.  If someone is still having this issue after updating please feel free to re-open.
