### ISSUE TITLE
Anchor tags considered as non-interactive element?

### ISSUE THREAD

**Issue by sriprabha** [reactjs/react-a11y#108]
I have a component that has an `a` tag with an `onClick` handler but no `href` attribute. `react-a11y` throws an error on this component, `You have a click handler on a non-interactive element but no`role`DOM property.` Is `role` and `tabindex` expected to be added for an anchor tag?

**Comment by alexlande** [comment]
If your `a` tag doesn't have an `href`, it should have a `role='button'` or similar (along with appropriate keyboard support to emulate button behavior).

An easier option would be to use a `button` element if there's no `href` and style it like a link, or however you like!

I wrote a blog post about this, if you're interested in more details: http://www.alexlande.com/articles/anchors-buttons-and-accessibility/
