### ISSUE TITLE
Unhandled Exception (Null result from ReactDOM.findDOMNode)

### ISSUE THREAD

**Issue by CoreyKumpAL** [reactjs/react-a11y#122]
[Line 51 of assertions.js](https://github.com/reactjs/react-a11y/blob/master/lib/assertions.js#L51) is generating an unhandled error when the result from `ReactDOM.findDOMNode(this)` on [line 104](https://github.com/reactjs/react-a11y/blob/master/lib/assertions.js#L104) is `null`. This is the message that I've been seeing in my console (note that line 794 in `react-a11y.js` corresponds to line 51 in this repo's `assertions.js`):

```
react-a11y.js:794 Uncaught TypeError: Cannot read property 'tagName' of null
```

---

Changing [line 65](https://github.com/reactjs/react-a11y/blob/master/lib/assertions.js#L65) to `if (context.passed || node === null)` bypasses this error entirely.

Alternatively, adding the following after [line 66](https://github.com/reactjs/react-a11y/blob/master/lib/assertions.js#L66) generates a message indicating that the element is unlabeled.

```
  if (node === null) {
    failureCB();
    return;
  }
```

**Comment by CoreyKumpAL** [comment]
Fixed by https://github.com/reactjs/react-a11y/pull/123

**Comment by Shastel** [comment]
Hi @wyattdanger as far as i can see fix is already merged, could you please explain why issue is still open?
