### ISSUE TITLE
Support React v15

### ISSUE THREAD

**Issue by incubus8** [reactjs/react-a11y#124]
Hi guys,

I am wondering. Is there any plan to support / update the latest React v15?

Thank you.

**Comment by tiemevanveen** [comment]
I've got no problem using the latest React v15..

**Comment by gavmck** [comment]
If you're getting the same ReactDOM issue I was, you have to pass in ReactDOM as an option.

`a11y(React, { ReactDOM: ReactDOM });`

**Comment by Swaagie** [comment]
Works fine with React@15 as far as I can tell. As long as you pass `ReactDOM` like gavmck suggested above. Made small improvement to documentation https://github.com/reactjs/react-a11y/pull/129

**Comment by erin-doyle** [comment]
This work around should not be needed anymore and v1.0.0 now fully supports React v16.  Please try upgrading to the latest version.  I'm closing this as I believe the issue is resolved in v1.0.0.  I'll reopen if I hear that's not the case.
