### ISSUE TITLE
no-static-element-interactions issue

### ISSUE THREAD

**Issue by linzhaoken** [reactjs/react-a11y#131]
The eslint waring no-static-element-interactions still show up with the proper attributes for div tag.
I have add onClick, onKeyPress and role attributes to div tag as recommended in https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-static-element-interactions.md, but still get warning

React version: 15.4.0
Eslint version: v3.19.0

Warning:
![screen shot 2017-05-16 at 8 55 31 am](https://cloud.githubusercontent.com/assets/4997989/26095815/ee5e4ff2-3a16-11e7-85c8-174d2af85f94.png)

My Code:
```
<div
    className="hb-card hb-card--goal"`}
    onClick={this.handleClick}
    onKeyPress={this.handleKeyPress}
    tabIndex="0"
    role="button"
>

**Comment by erin-doyle** [comment]
This is coming from the [eslint-plugin-jsx-a11y](https://github.com/evcohen/eslint-plugin-jsx-a11y) library and not react-a11y.  You will need to go to that repo and log the issue there.
