### ISSUE TITLE
Uncaught TypeError: reactComponent.getName is not a function (React 16)

### ISSUE THREAD

**Issue by smacpherson64** [reactjs/react-a11y#137]
Hello, I have been experiencing an error when using `react-a11y` with React 16.

It seems the issue is: `reactComponent.getName()` in `lib/index.js` on line 137 is undefined in React 16.

Below is a concept that may help resolve the issue.
```
  // Validate component name against React Version
  // Version <= 15 use reactComponent.getName()
  // Version >= 16 use reactComponent.type.name
  var reactComponentName = Boolean(reactComponent.type)
    ? reactComponent.type.name
    : reactComponent.getName();

  // If a Component instance, use the component's name,
  // if a ReactElement instance, use the tag name + id (e.g. div#foo)
  var name = reactComponent && reactComponentName || type + '#' + props.id;
```

**Comment by reintroducing** [comment]
Also running into this which makes react-a11y unusable with React 16, unfortunately. I have to disable it until this is fixed.

**Comment by heatherbooker** [comment]
Looks like it would be fixed by https://github.com/reactjs/react-a11y/pull/139; anything we can do to support this fix getting merged? :)

**Comment by erin-doyle** [comment]
Please try updating to v1.0.0 as this issue should now be fixed.  Let me know if not and I'll reopen this.
