### ISSUE TITLE
React version compatibility

### ISSUE THREAD

**Issue by ebednarz** [reactjs/react-a11y#154]
When I add `react-a11y` to my project, it breaks because `ref`s created with  `React.createRef()` appear not to be supported. Could you

a) verify that, and if so
b) add a note about version/API compatibility to the README?

Thanks. :-)

**Comment by erin-doyle** [comment]
I am not yet aware of any issues with `React.createRef()` but there certainly may be.  I will do some testing and look into it.  Can you provide any more details though to help out?  What are you seeing when you say "it breaks"?  Is there an error?  Or is something else not working?  What version of `react-a11y` and what version of `React` are you using?

**Comment by ebednarz** [comment]
Fair enough, please see https://github.com/ebednarz/a11y-createref for a minimal reproduction case.

**Comment by erin-doyle** [comment]
This is super helpful, thanks for putting this together @ebednarz .  I'll dig into it as soon as I can!

**Comment by remisture** [comment]
+1

**Comment by erin-doyle** [comment]
Yep you're right there was a bug with handling createRef() and I have pushed a fix here: https://github.com/reactjs/react-a11y/commit/c45ed13770275f75b187768717cc4ad6aa82dfdc.  I will be publishing a new version to npm shortly.

**Comment by erin-doyle** [comment]
Ok 1.1.0 has been published with this fix!
