### ISSUE TITLE
Broken, outdated external links

### ISSUE THREAD

**Issue by SeanMcP** [reactjs/react-a11y#160]
Scanning through the project, I found a number of broken (404) and/or outdated external links. I'm preparing a pull request to make those updates, but have come across two instances that require some decision making:

1. [`w3.org/TR/wai-aria-practices/#focus_tabindex`](http://www.w3.org/TR/wai-aria-practices/#focus_tabindex)
   - **Explanation** - This link no longer refers to an anchor on the page. The later reference to both "focus" and "tabindex" seems pretty specific to using a [roving tabindex](https://www.w3.org/TR/wai-aria-practices/#kbd_roving_tabindex).
   - **References**
      - https://github.com/reactjs/react-a11y/blob/fb2f4df1a3b0f23ee3c683f4206345bf099d63cc/src/rules/onclick-uses-tabindex.js#L13
      - https://github.com/reactjs/react-a11y/blob/master/docs/rules/deprecated/onclick-uses-tabindex.md
      - https://github.com/reactjs/react-a11y/blob/fb2f4df1a3b0f23ee3c683f4206345bf099d63cc/src/rules/interactive-supports-focus.js#L12
      - https://github.com/reactjs/react-a11y/blob/master/docs/rules/interactive-supports-focus.md
2. [`w3.org/TR/html-alt-techniques/`](https://www.w3.org/TR/html-alt-techniques/)
   - **Explanation** - This page has been retired/discontinued. The page offers a link to the [alt attribute guidelines](https://www.w3.org/TR/html51/semantics.html#alt), but even that appears broken.
   - **References**
      - https://github.com/reactjs/react-a11y/blob/fb2f4df1a3b0f23ee3c683f4206345bf099d63cc/src/rules/img-uses-alt.js#L11
      - https://github.com/reactjs/react-a11y/blob/master/docs/rules/img-uses-alt.md

I see three options here:
   1. Use [Wayback Machine](https://archive.org/web/) or some equivalent to find a usable page with the current links
   2. Find new links that refer to similar content
   3. (In the case of the deprecated rule) Leave the broken link

Of those options, I think two is the best. It will provide up-to-date information for the end user, including contextual information should they look around the site.

What do you all think?

**Comment by erin-doyle** [comment]
Thank you so much for your help with this @SeanMcP !  I had no idea these links were dead so this is great that you're offering to clean them up!  I think I've found appropriate new links for these rules.  Here's what I think we should do:

- onclick-uses-tabindex/interactive-supports-focus (yes let's update the deprecated one too):
-- https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#ax_focus_02
-- https://www.w3.org/TR/wai-aria-practices-1.1/#kbd_generalnav
- img-uses-alt:
-- https://dequeuniversity.com/rules/axe/2.1/image-alt
