### ISSUE TITLE
no-positive-index and aria-role rules warn/error when passing undefined as props for role and tabIndex

### ISSUE THREAD

**Issue by pachuka** [reactjs/react-a11y#161]
I have a custom component that is used in multiple places, so I'd like to pass down the tabIndex and role property as props. When tabIndex and role are not passed in they default to undefined, but this is still causing the react-a11y to trigger the warnings/errors even though this is a valid case.

Elements with ARIA roles must use a valid, non-abstract ARIA role.
Avoid positive integer values for `tabIndex`.

Ex:

```jsx
render() {
    <div tabIndex={this.props.tabIndex} role={this.props.role}>
       ....
    </div>
}
```

I don't think this should be triggering the warning/error.

**Comment by erin-doyle** [comment]
Ok I'm not totally following your example here.  Are you getting the warnings when `tabIndex` and `role` are `undefined` or when they have actual values?  If it's when they are `undefined` I would suggest defaulting these props to `null` instead.  If it's when they have values can you give me some examples of values that are triggering the warning?

**Comment by pachuka** [comment]
Sorry for not being explicit.

If I do:
```jsx
<Component />
// vs.
<Component role="link" tabIndex={0}/>
```
without explicitly passing tabIndex and role, those default to undefined.
In this case I get warnings for both of these fields.

Internally to the component if I update the default values:
```jsx
render() {
    <div tabIndex={this.props.tabIndex ? this.props.tabIndex: null} role={this.props.role ? this.props.role : null}>
       ....
    </div>
}
```
That resolves the `tabIndex` warning/error, but I still get the `Elements with ARIA roles must use a valid, non-abstract ARIA role` warning/error.

**Comment by erin-doyle** [comment]
Ok so I think probably what's happening is that even though React knows to exclude attributes from an element when the value is `null`, react-a11y is inspecting the elements perhaps before that happens.  What I would suggest you do with attributes like this would be to only include them when they have a value, like this:

```javascript
render() {
    const componentProps = {};
    if (this.props.tabIndex) {
        componentProps.tabIndex = this.props.tabIndex;
    }
    if (this.props.role) {
        componentProps.role = this.props.role;
    }

    return (
        <div {...componentProps} >
        ...
        </div>
    );
}
```

**Comment by pachuka** [comment]
That makes sense, thanks!

**Comment by erin-doyle** [comment]
Great I'm glad to hear it!  Ok I'll try to think of how to put this in the documentation in a way that will be helpful.
