### ISSUE TITLE
Level of conformity

### ISSUE THREAD

**Issue by dalefrancis88** [reactjs/react-a11y#163]
Hey, I'm sure this is somewhere but i just can't find it, sorry if it's somewhere obvious. 

What level on conformity does this ensure you hit if the application runs and there are no warnings?

https://www.w3.org/WAI/WCAG2AAA-Conformance

I also get that there are some things that may not be covered until render

**Comment by erin-doyle** [comment]
1. 

Nope this is not a claim that this library is making anywhere so you're not missing it.  This library is only able to catch a percentage of things that can be detected in the code at runtime that are known to cause accessibility problems.  There is a whole scope of problems it cannot test for.  So you should not depend on this library alone and assume that if you see no warnings your application is compliant to any level of standards conformance, that's just not possible.  I would recommend using this tool in conjunction with the following to best achieve compliance:

1. [eslint-plugin-jsx-a11y](https://github.com/evcohen/eslint-plugin-jsx-a11y) - for static code analysis
2. The [aXe browser plugin](https://www.deque.com/axe/) - use to audit each page/state of your application for accessibility findings listing what level/standard is being violated and the severity along with explanations of why it's important and suggestions on how to fix
3. Manual testing

You can only use automation to catch so many accessibility issues and you definitely should employ tools to help catch all of the low hanging fruit but ultimately you'll still need to identify usability issues by testing using the Assistive Technologies being used by your users (screen readers, Microsoft High Contrast Mode or other high contrast plugins, zoom text, navigating using a keyboard only, etc).

You may even need to use a licensed tool or have an audit performed by a company that has the ability to provide you with a certification for level of compliance if that's necessary for your application.  Though know that any certification is only good at that moment in time.  As soon as you make a code change the level of compliance may change.  So it's a point in time certification or percentage of compliance.

**Comment by dalefrancis88** [comment]
Hey @erin-doyle, That is a really well thought out and detailed response, i'm sure it took time to write out. I appreciate that you did it. 

I currently have both of those in the project to catch as many as possible. The main core concern of the question was to work out what I could "claim" we're compliant for by using this collection, however your response helps me understand more about how to approach this. Thank you
