### ISSUE TITLE
Hey, new committers, read the CONTRIBUTING.md

### ISSUE THREAD

**Issue by ryanflorence** [reactjs/react-a11y#40]
And then we'll get beautiful automatic changelogs, that is all :)

https://github.com/rackt/react-a11y/blob/master/CONTRIBUTING.md#commit-subjects-for-public-api-changes

**Comment by nickmccurdy** [comment]
Note that GitHub now links to CONTRIBUTING.md in the "New issue" UI, so this should be easier to discover.
