### ISSUE TITLE
Use React.findDOMNode to log element references

### ISSUE THREAD

**Issue by kloots** [reactjs/react-a11y#54]
When there's an error, we currently use document.getElementById to log element element references. Since the code is executed in a componentDidMount/componentDidUpdate callback, we could use React.findDOMNode() instead.

**Comment by alexlande** [comment]
Between this and #55, would that mean that ID generation was no longer necessary?

If that was the case, I think it would indirectly resolve a few currently open issues: #77, #79, #85

I could take a shot at this if you'd like, @kloots.

**Comment by dmitrif** [comment]
Hi, guys!

Has there been any changes in regards to this?

Thanks.

**Comment by erin-doyle** [comment]
I believe as of v1.0.0 we are no longer using document.getElementById for anything.  I'm going to go ahead and close this but please let me know if you disagree.
