### ISSUE TITLE
Add tests to warn against use of an explicit tabIndex

### ISSUE THREAD

**Issue by kloots** [reactjs/react-a11y#66]
[Setting tabIndex to an explicit value should be avoided](http://www.paciellogroup.com/blog/2014/08/using-the-tabindex-attribute/), we should add tests for this.

**Comment by erin-doyle** [comment]
When you say explicit value to you mean positive integer?  I think there are many valid use cases for setting it to 0 or -1 and we shouldn't prevent that.

**Comment by erin-doyle** [comment]
I agree we could add a warning for when the tabIndex is a positive integer.

**Comment by erin-doyle** [comment]
Apparently this rule had already been added in v1.0.0 but because the rule documentation page was missing I didn't realize it.  I've added it in the merged PR linked.
