### ISSUE TITLE
assertions.js failing with "TypeError: Cannot read property 'children' of undefined"

### ISSUE THREAD

**Issue by EvHaus** [reactjs/react-a11y#71]
This bit of code in assertions.js is failing for me in some cases:

```
var hasChildTextNode = function hasChildTextNode(props, children) {
  var hasText = false;
  React.Children.forEach(children, function (child) {
    if (hasText) return;else if (child === null) return;else if (typeof child === 'undefined') return;else if (typeof child === 'string') hasText = true;else if (child.type === 'img' && child.props.alt) hasText = true;else if (child.props.children) hasText = hasChildTextNode(child.props, child.props.children);
  });
  return hasText;
};
```

The error I get is: `TypeError: Cannot read property 'children' of undefined`.

I've isolated it down to a node with some text in it. I don't see anything special about it, but removing that node makes the issue go away.

_EDIT_ More info. It seems to be related to text which is an integer:

```
// This will cause an error
var x = 1;
return (
    <button>
        <span>{x}</span>
    </button>
)

// However, this is totally okay
var x = 1;
return (
    <button>
        <span>{x.toString()}</span>
    </button>
)

```

**Comment by erin-doyle** [comment]
A lot has changed since this was posted.  I'm going to close for now as I'm assuming this is no longer an issue.  If you are still running into it please feel free to re-open.
