### ISSUE TITLE
Specify babel-runtime as a dependency or a peer dependency

### ISSUE THREAD

**Issue by mathieumg** [reactjs/react-a11y#72]
Since 0.2.x it seems this depends on the `babel-runtime` module being available at runtime. Should it be moved to the regular dependencies or even the peer dependencies in the package.json?

**Comment by AsaAyers** [comment]
Peer dependencies are getting removed in npm 3. No real solution is being
offered as far as I can tell, just removing what works.

**Comment by mathieumg** [comment]
They're not getting removed, they're getting fixed. Instead of installing under themselves a peer dependency that isn't already provided, they will just error in that case. In other words, you must provide the dependencies listed as peer by yourself. I think it's a good change. That being said, react-a11y currently crashes if you don't have `babel-runtime` installed and it's only listed as being a peer dependency, that is certainly wrong.

**Comment by taddei** [comment]
+1

**Comment by AsaAyers** [comment]
See https://github.com/rackt/react-a11y/pull/74 github has a built in editor, you don't even have to checkout the project to fix this.

**Comment by mathieumg** [comment]
This was to discuss whether it should be a peer dependency or a dependency. I think peer makes sense.

**Comment by AsaAyers** [comment]
I'm not sure requiring the runtime is even a good idea. IDK about webpack but I think browserify is only going to package a single version of any given module.

I think since this requires `babel-runtime@^5.1.11` it means if I'm writing something that uses `react-a11y` I'm going to have to use the same version. I don't think it makes any diffrence in that situation whether it's a peer or not.

**Comment by mathieumg** [comment]
> it means if I'm writing something that uses react-a11y I'm going to have to use the same version

Usually peer dependencies try to be generally vague in their semver unless something is known to break. The semver for the peer dependency of `babel-runtime` could be `>= 5.0.0` for all we know.

**Comment by davidgilbertson** [comment]
Hmm, it seems odd to me that this lib simply doesn't work out of the box. Could this at least be a note in the `readme`?

"To use `react-a11y` you must have `babel-runtime` installed"? Or am I missing something?

**Comment by AsaAyers** [comment]
Any plans on releasing a version that works with Babel6? Since you depend on `babel-runtime@5` it doesn't seem like anyone using `react-a11y` can upgrade to Babel6 even though the two things should be completely unrelated to each other.

**Comment by erin-doyle** [comment]
`babel-runtime` is now a devDependency in v1.0.0 and seems to work fine where I've used it in applications running Babel6.  I'm going to close this as I don't believe it's an issue any longer in the latest v1.0.0.  Please respond back here if anyone is still having this problem.
