### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by badtant** [reactjs/react-a11y#78]
Hi,

I tried to upgrade from 0.1.1 to 0.2.6.
First my att didn't even start until I added babel-runtime as a dep. Now the app starts but I get the following error:

Chrome:
Uncaught RangeError: Maximum call stack size exceeded
(anonymous function)    @   client.bundle.js:1
React.createElement @   index.js:171
React.createElement @   index.js:172
React.createElement @   index.js:172
React.createElement @   index.js:172
React.createElement @   index.js:172
React.createElement @   index.js:172
React.createElement @   index.js:172
...

Firefox:
too much recursion

Node: 0.12.5
React 0.13.3

**Comment by erin-doyle** [comment]
The library has been updated and many other things have been updated since this was posted.  I'd ask that you update to the latest version of react-a11y and try again.  I'm going to close this now but please re-open if you're still running in to this.
