### ISSUE TITLE
Different react-a11y ids (server side render)

### ISSUE THREAD

**Issue by mykhailo-riabokon** [reactjs/react-a11y#85]
I am using React in isomorphic way, and have met warning message, after server side rendering. (You can reach message in attachments). How can I set react-a11 on client and on server? Thank you.
<img width="1431" alt="2015-07-29 15 47 25" src="https://cloud.githubusercontent.com/assets/10687640/8958128/aa176830-360b-11e5-82dc-718b3172c323.png">

**Comment by mathieumg** [comment]
I have the same problem!

**Comment by scsper** [comment]
I am also having this issue.

**Comment by jasonmit** [comment]
A solution could be using a hash derived from the `textContent` within the wrapping element which react-a11y creates.  This should mean the IDs will match (I would hope so at least..).  Thoughts?

**Comment by m14t** [comment]
@jasonmit I realize this issue is a little old, but did you verify that this solution worked? Any details on how to opt in to this?

**Comment by konojunya** [comment]
Was this problem solved by [romeovs/react-a11y](https://github.com/romeovs/react-a11y) ?
