### ISSUE TITLE
No ID listed in warnings

### ISSUE THREAD

**Issue by AsaAyers** [reactjs/react-a11y#86]
I added the ID back in #14 so we could actually find the elements producing warnings.

![selection_195](https://cloud.githubusercontent.com/assets/324999/8990928/5a3e56a8-36c3-11e5-9526-5740480182fe.png)

What's the point of warning without a direct reference to where it's being produced?

Putting the ID only on elements that were failing was great because I had some CSS targeting `*[id^=a11y-] {` which would cause broken elements to fade in and out so you could find them. The animation is also very irritating which motivates fixing it immediately. 

So now after upgrading I can't find the elements throwing warnings and I can't style broken elements.

**Comment by blairanderson** [comment]
you should activate this option `a11y(React, { includeSrcNode: true });`

**Comment by joeybaker** [comment]
@blairanderson what does that option do? It doesn't seem to be documented?

**Comment by AsaAyers** [comment]
I belive I did. That's why this is prefixed with `Pushmenu`, but that doesn't actually help me find the element, just the Component.

I ran into enough problems trying to upgrade it made more sense to just give up and go back to my old fork of the project.

**Comment by joeybaker** [comment]
@AsaAyers are you maintaining your fork? This repo hasn't gotten much love :\

**Comment by AsaAyers** [comment]
No, I had to create a fork when I had a bunch of PRs here that weren't merged. They have been merged, but everything I've done has been changed. What I can say is that my fork works for my project and this version doesn't any more. It was more work than I'm willing to do to change that.

**Comment by joeybaker** [comment]
Got it, thanks.

**Comment by blairanderson** [comment]
@joeybaker It shows the offending HTML element...

<img width="1072" alt="screen shot 2015-09-01 at 12 53 20 am" src="https://cloud.githubusercontent.com/assets/955736/9598859/057baf9a-5044-11e5-9bcb-30dc16621a48.png">


its documented on the README:

>If you want to log DOM element references for easy lookups in the DOM inspector, use the includeSrcNode option.

`a11y(React, { throw: true, includeSrcNode: true });`

**Comment by erin-doyle** [comment]
I believe this has been answered and the reporting has changed since this was posted.  I'm going to close this now but please feel free to re-open if you're still having issues with the latest version.
