### ISSUE TITLE
"Uncaught RangeError: Maximum call stack size exceeded" after hot reloading with webpack

### ISSUE THREAD

**Issue by gtoma4** [reactjs/react-a11y#94]
I am using webpack 1.12.2, webpack-dev-server 1.11.0, and react-hot-loader 1.3.0.  If I change an element in a component and that component is updated (not the whole page), I get this error.  If I refresh the page in the browser window, everything works as expected.

Has anyone else used webpack and hot loading successfully?

**Comment by erin-doyle** [comment]
This doesn't sound like an issue with `react-a11y` and those versions are fairly old at this time.  I'm going to close this but feel free to reopen if it's still an issue with more recent versions of webpack.
