### ISSUE TITLE
When passing an onClick prop down to a child DOM node, a11y expects a role property on the parent.

### ISSUE THREAD

**Issue by Jon-Biz** [reactjs/react-a11y#95]
Passing an onClick to a component with the following render method triggers a 

`a11y-0 You have a click handler on a non-interactive element but no`role`DOM property...`

warning:

``` javascript
  render () {
    return (
      <li>
        <span ref="span" onClick={this.props.onClick} aria-label="Link" role="button" >
         {this.props.title
        </span>
      </li>
    )
  }
```

Passing in a click handler called something other than `onClick` does not render a warning, even if the `aria-label` and `role` is removed. This is also a problem.

**Comment by erin-doyle** [comment]
When a prop is named `onClick` React specifically registers that function as the handler of the click event on that element automatically.  So if you don't want to register an `onClick` handler on an element but simply wish to pass that function down to a child do not call that prop `onClick`.  Accessibility only needs to be a concerned when you are actually doing the event handler registering which is when you assign the function to the `onClick` prop.  If the prop is named anything else then it is not yet an Accessibility concern as it's not actually an event handler yet.
